name: Push Helm chart oci image to Google Artifact Registry Reusable Workflow

permissions:
  contents: read
  id-token: write

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      chart_version:
        required: true
        type: string
    secrets:
      ARTIFACT_REGISTRY_HOST_NAME:
        required: true
      PROJECT_ID:
        required: true
      WI_POOL_PROVIDER_ID:
        required: true
      PACKAGER_GSA_ID:
        required: true
      HELM_REPO_ID:
        required: true

jobs:
  helm-push-to-oci-gar:
    env:
      OCI_REPO_NAME: "oci://${{ secrets.ARTIFACT_REGISTRY_HOST_NAME }}/${{ secrets.PROJECT_ID }}/${{ secrets.HELM_REPO_ID }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: '${{ secrets.WI_POOL_PROVIDER_ID }}'
          service_account: '${{ secrets.PACKAGER_GSA_ID }}'
          token_format: 'access_token'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: latest

      - name: Login to GCP Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.ARTIFACT_REGISTRY_HOST_NAME }} --quiet
          
      - name: Helm package
        run: |
          helm package infra/${{ inputs.app_name }} --version ${{ inputs.chart_version  }}

      - name: Helm push
        run: |
          helm push ${{ inputs.app_name }}-${{ inputs.chart_version  }}.tgz ${{ env.OCI_REPO_NAME }} --debug