name: Push Docker image to Google Artifact Registry Reusable Workflow

permissions:
  contents: 'read'
  id-token: 'write'
  attestations: 'write'

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      build_id:
        required: true
        type: string
      context:
        required: false
        type: string
        default: .
      dockerfile:
        required: false
        type: string
        default: Dockerfile
      sbom:
        required: false
        type: boolean
        default: true
      provenance:
        required: false
        type: boolean
        default: true
      push:
        required: false
        type: boolean
        default: true
      labels:
        required: false
        type: string
    secrets:
      ARTIFACT_REGISTRY_HOST_NAME:
        required: true
      PROJECT_ID:
        required: true
      WI_POOL_PROVIDER_ID:
        required: true
      PACKAGER_GSA_ID:
        required: true
      IMAGE_REPO_ID:
        required: true

jobs:
  build-and-push-docker-gar:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: "australia-southeast2-docker.pkg.dev/effortless-city-458902-q8/cmek-container-images/go-demo-app"
    steps:

      # Configure Docker to authenticate to Google Artifact Registry
      - name: Clean Docker config
        run: |
          rm -rf /home/runner/.docker

      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Authenticate to Google Cloud using OIDC
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ secrets.WI_POOL_PROVIDER_ID }}'
          service_account: '${{ secrets.PACKAGER_GSA_ID }}'
          token_format: 'access_token'

      # Set up Docker Buildx for advanced build capabilities
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Configure Docker for GAR properly
      - name: Fix Docker auth for GAR
        run: |
          # First, ensure we are starting with a clean config
          mkdir -p /home/runner/.docker
          echo '{"credHelpers":{"${{ secrets.ARTIFACT_REGISTRY_HOST_NAME }}":"gcloud"}}' > /home/runner/.docker/config.json
          
          # Configure Docker to use gcloud credential helper
          gcloud auth configure-docker ${{ secrets.ARTIFACT_REGISTRY_HOST_NAME }} --quiet

      # Print Docker config for debugging
      - name: Print Docker config
        run: |
          cat /home/runner/.docker/config.json

      # Explicit login for both Docker and attestation to use
      - name: Login to Google Artifact Registry
        id: login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ARTIFACT_REGISTRY_HOST_NAME }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      # Print Docker config after login for debugging
      - name: Print Docker config after login
        run: |
          cat /home/runner/.docker/config.json

      # Build and push the Docker image to Google Artifact Registry, generating provenance and SBOM
      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          push: ${{ inputs.push }}
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          tags: |
            ${{ env.IMAGE_NAME }}:${{ inputs.build_id }}
            ${{ env.IMAGE_NAME }}:latest
          labels: ${{ inputs.labels }}
          provenance: ${{ inputs.provenance }}
          sbom: ${{ inputs.sbom }}

      # Publish a provenance attestation for the built image with custom token
      - name: Publish image attestations
        if: inputs.push == true
        uses: actions/attest-build-provenance@v2
        env:
          DOCKER_CONFIG: /home/runner/.docker
        with:
          subject-name: ${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.build-and-push.outputs.digest }}
          push-to-registry: true
          registry-username: oauth2accesstoken
          registry-password: ${{ steps.auth.outputs.access_token }}